In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import pandas as pd

### e.g : However Zenit St. Petersburg and Moldovan side FC Sheriff are not in FIFA 22.I just have made this humble DataFrame for my own. If you could need or consult it, feel free to enhance and implement it. Good Luck!

In [3]:
df= pd.DataFrame(columns = ["short_name","age","nationality","player_positions","overall","potential","club_jersey_number",
                            "value_eur","wage_eur","club_contract_valid_until","international_reputation",
                            "release_clause_eur","club_loaned_from"])

df.loc[0] = ["Stanislav Kritsyuk",31,"Russia","GK","Nan","Nan",1.0,2500000,"Nan",2022.0,"Nan","Nan","Nan"]
df.loc[1] = ["Dmitriy Chistyakov",27,"Russia","DF","Nan","Nan",2.0,2800000,"Nan",2025.0,"Nan","Nan","Nan"]
df.loc[2] = ["Douglas Santos",27,"Brasil","DF","Nan","Nan",3.0,16000000,"Nan",2026.0,"Nan","Nan","Nan"]
df.loc[3] = ["Danil Krugovoy",23,"Russia","DF","Nan","Nan",4.0,1500000,"Nan",2024.0,"Nan","Nan","FC Ufa"]
df.loc[4] = ["Wilmar Barrios",28,"Colombia","MF","Nan","Nan",5.0,18000000,"Nan",2026.0,"Nan","Nan","Nan"]
df.loc[5] = ["Dejan Lovren",32,"Croatia","DF","Nan","Nan",6.0,10000000,"Nan",2023.0,"Nan","Nan","Nan"]
df.loc[6] = ["Serdar Azmoun",26,"Iran","FW","Nan","Nan",7.0,25000000,"Nan",2023.0,"Nan","Nan","Nan"]
df.loc[7] = ["Wendel",24,"Brasil","MF","Nan","Nan",8.0,18000000,"Nan",2025.0,"Nan","Nan","Nan"]
df.loc[8] = ["Malcom",24,"Brasil","FW","Nan","Nan",10.0,22000000,"Nan",2024.0,"Nan","Nan","Nan"]
df.loc[9] = ["Claudinho",24,"Brasil","MF","Nan","Nan",11.0,11000000,"Nan",2026.0,"Nan","Nan","Nan"]
df.loc[10] = ["Daler Kuzyaev",28,"Russia","MF","Nan","Nan",14.0,8000000,"Nan",2023.0,"Nan","Nan","Nan"]
df.loc[11] = ["Vyacheslav Karavaev",26,"Russia","DF","Nan","Nan",15.0,7000000,"Nan",2023.0,"Nan","Nan","Nan"]
df.loc[12] = ["Andrey Mostovoy",23,"Russia","MF","Nan","Nan",17.0 ,3000000,"Nan",2024.0,"Nan","Nan","PFC Sochi"]
df.loc[13] = ["Aleksey Sutormin",27,"Russia","MF","Nan","Nan",19.0,2500000,"Nan",2022.0,"Nan","Nan","Nan"]
df.loc[14] = ["Aleksandr Erokhin",32,"Russia","MF","Nan","Nan",21.0,3000000,"Nan",2022.0,"Nan","Nan","Nan"]
df.loc[15] = ["Artёm Dzyuba",33,"Russia","FW","Nan","Nan",22.0,10000000,"Nan",2022.0,"Nan","Nan","FC Arsenal Tula"]
df.loc[16] = ["Magomed Ozdoev",28,"Russia","MF","Nan","Nan",27.0 ,5000000,"Nan",2022.0,"Nan","Nan","FC Akhmat Grozny"]
df.loc[17] = ["Mikhail Kerzhakov",34,"Russia","GK","Nan","Nan",41.0,1500000,"Nan",2022.0,"Nan","Nan","FC Orenburg"]
df.loc[18] = ["Yaroslav Rakitskiy",32,"Ukranie","DF","Nan","Nan",44.0,6000000,"Nan",2022.0,"Nan","Nan","Nan"]
df.loc[19] = ["Kirill Kravtsov",19,"Russia","DF","Nan","Nan",64.0,300000,"Nan",2024.0,"Nan","Nan","Nan"]
df.loc[20] = ["Daniil Odoevskiy",18,"Russia","GK","Nan","Nan",71.0,250000,"Nan",2024.0,"Nan","Nan","Nan"]
df.loc[21] = ["Daniil Kuznetsov",18,"Russia","FW","Nan","Nan",85.0,150000,"Nan",2025.0,"Nan","Nan","Nan"]
df.loc[22] = ["David Byazrov","Nan","Russia","GK","Nan","Nan",92.0,75000,"Nan",2025.0,"Nan","Nan","Nan"]
df.loc[23] = ["Danila Khotulёv",19,"Russia","DF","Nan","Nan",94.0,"Nan","Nan","Nan","Nan","Nan","Nan"]

FC_Zenit = df
FC_Zenit

,short_name,age,nationality,player_positions,overall,potential,club_jersey_number,value_eur,wage_eur,club_contract_valid_until,international_reputation,release_clause_eur,club_loaned_from
0,Stanislav Kritsyuk,31,Russia,GK,Nan,Nan,1.0,2500000,Nan,2022.0,Nan,Nan,Nan
1,Dmitriy Chistyakov,27,Russia,DF,Nan,Nan,2.0,2800000,Nan,2025.0,Nan,Nan,Nan
2,Douglas Santos,27,Brasil,DF,Nan,Nan,3.0,16000000,Nan,2026.0,Nan,Nan,Nan
3,Danil Krugovoy,23,Russia,DF,Nan,Nan,4.0,1500000,Nan,2024.0,Nan,Nan,FC Ufa
4,Wilmar Barrios,28,Colombia,MF,Nan,Nan,5.0,18000000,Nan,2026.0,Nan,Nan,Nan
5,Dejan Lovren,32,Croatia,DF,Nan,Nan,6.0,10000000,Nan,2023.0,Nan,Nan,Nan
6,Serdar Azmoun,26,Iran,FW,Nan,Nan,7.0,25000000,Nan,2023.0,Nan,Nan,Nan
7,Wendel,24,Brasil,MF,Nan,Nan,8.0,18000000,Nan,2025.0,Nan,Nan,Nan
8,Malcom,24,Brasil,FW,Nan,Nan,10.0,22000000,Nan,2024.0,Nan,Nan,Nan
9,Claudinho,24,Brasil,MF,Nan,Nan,11.0,11000000,Nan,2026.0,Nan,Nan,Nan
10,Daler Kuzyaev,28,Russia,MF,Nan,Nan,14.0,8000000,Nan,2023.0,Nan,Nan,Nan
11,Vyacheslav Karavaev,26,Russia,DF,Nan,Nan,15.0,7000000,Nan,2023.0,Nan,Nan,Nan
12,Andrey Mostovoy,23,Russia,MF,Nan,Nan,17.0,3000000,Nan,2024.0,Nan,Nan,PFC Sochi
13,Aleksey Sutormin,27,Russia,MF,Nan,Nan,19.0,2500000,Nan,2022.0,Nan,Nan,Nan
14,Aleksandr Erokhin,32,Russia,MF,Nan,Nan,21.0,3000000,Nan,2022.0,Nan,Nan,Nan
15,Artёm Dzyuba,33,Russia,FW,Nan,Nan,22.0,10000000,Nan,2022.0,Nan,Nan,FC Arsenal Tula
16,Magomed Ozdoev,28,Russia,MF,Nan,Nan,27.0,5000000,Nan,2022.0,Nan,Nan,FC Akhmat Grozny
17,Mikhail Kerzhakov,34,Russia,GK,Nan,Nan,41.0,1500000,Nan,2022.0,Nan,Nan,FC Orenburg
18,Yaroslav Rakitskiy,32,Ukranie,DF,Nan,Nan,44.0,6000000,Nan,2022.0,Nan,Nan,Nan
19,Kirill Kravtsov,19,Russia,DF,Nan,Nan,64.0,300000,Nan,2024.0,Nan,Nan,Nan
20,Daniil Odoevskiy,18,Russia,GK,Nan,Nan,71.0,250000,Nan,2024.0,Nan,Nan,Nan
21,Daniil Kuznetsov,18,Russia,FW,Nan,Nan,85.0,150000,Nan,2025.0,Nan,Nan,Nan
22,David Byazrov,Nan,Russia,GK,Nan,Nan,92.0,75000,Nan,2025.0,Nan,Nan,Nan
23,Danila Khotulёv,19,Russia,DF,Nan,Nan,94.0,Nan,Nan,Nan,Nan,Nan,Nan

In [4]:

df= pd.DataFrame(columns = ["short_name","age","nationality","player_positions","overall","potential","club_jersey_number",
                            "value_eur","wage_eur","club_contract_valid_until","international_reputation",
                            "release_clause_eur","club_loaned_from"])

df.loc[0] = ["Dumitru Celeadnic",29,"Moldova","GK","Nan","Nan",1.0,225000,"Nan","Nan","Nan","Nan","Nan"] 
df.loc[1] = ["Danilo Arboleda",26,"Colombia","DF","Nan","Nan",2.0,1200000,"Nan","Nan","Nan","Nan","Nan"] 
df.loc[2] = ["Charles Petro",20,"Malawi","DF","Nan","Nan",3.0,400000,"Nan",2022.0,"Nan","Nan","Nan"]
df.loc[3] = ["Stjepan Radeljić",24,"Bosnia and Herzegovina","DF","Nan","Nan",6.0,350000,"Nan",2021.0,"Nan","Nan","NK Osijek"]
df.loc[4] = ["Basit Khalid",25,"Ghana","FW","Nan","Nan",7.0,700000,"Nan",2024.0,"Nan","Nan","Nan"]
df.loc[5] = ["Alexandr Belousov",23,"Moldova","DF","Nan","Nan",8.0,300000,"Nan","Nan","Nan","Nan","Dinamo-Auto Tiraspol"]
df.loc[6] = ["Adama Traoré",26,"Mali","FW","Nan","Nan",9.0,2500000,"Nan",2022.0,"Nan","Nan","FC Metz"]
df.loc[7] = ["Frank Castañeda",27,"Colombia","FW","Nan","Nan",10.0,1200000,"Nan",2021.0,"Nan","Nan","Senica"]
df.loc[8] = ["Lovro Bizjak",27,"Slovenia","FW","Nan","Nan",11.0,400000,"Nan",2022.0,"Nan","Nan","Nan"]
df.loc[9] = ["Abdoul Moumouni",19,"Niger","MF","Nan","Nan",12.0,150000,"Nan",2024.0,"Nan","Nan","Nan"]
df.loc[10] = ["Fernando Costanza",22,"Brasil","DF","Nan","Nan",13.0,800000,"Nan","Nan","Nan","Nan","LOSC Lille"]
df.loc[11] = ["Cristiano",28,"Brasil","DF","Nan","Nan",15.0,2000000,"Nan",2022.0,"Nan","Nan","Nan"]
df.loc[12] = ["Keston Julien",22,"Trinidad and Tobago","DF","Nan","Nan",16.0,450000,"Nan",2023.0,"Nan","Nan","Nan"]
df.loc[13] = ["Jasur Yakhshiboev",24,"Uzbekistan","FW","Nan","Nan",17.0,700000,"Nan",2022.0,"Nan","Nan","Legia Warsaw"]
df.loc[14] = ["Moussa Kyabou",23,"Mali","MF","Nan","Nan",18.0,350000,"Nan",2021.0,"Nan","Nan","USC Kita"]
df.loc[15] = ["Serafim Cojocari",20,"Moldavia","MF","Nan","Nan",19.0,100000,"Nan","Nan","Nan","Nan","Nan"]
df.loc[16] = ["Boban Nikolov",27,"Macedonia","MF","Nan","Nan",20.0,800000,"Nan",2022.0,"Nan","Nan","Nan"]
df.loc[17] = ["Edmund Addo",21,"Ghana","MF","Nan","Nan",21.0,"Nan",1100000,"Nan",2024.0,"Nan","Nan"]
df.loc[18] = ["Dimitrios Kolovos",28,"Greece","MF","Nan","Nan",22.0,1000000,"Nan",2022.0,"Nan","Nan","Nan"]
df.loc[19] = ["Nadrey Dago",24,"Ivory Coast","FW","Nan","Nan",23.0,300000,"Nan",2023.0,"Nan","Nan","NK Dugopolje"]
df.loc[20] = ["Dušan Marković",23,"Serbia","GK","Nan","Nan",26.0,250000,"Nan","Nan","Nan","Nan","Nan"]
df.loc[21] = ["Giorgos Athanasiadis",28,"Greece","GK","Nan","Nan",30.0,1500000,"Nan",2022.0,"Nan","Nan","AEK Athens"]
df.loc[22] = ["Sébastien Thill",27,"Luxembourg","MF","Nan","Nan",31.0,1000000,"Nan",2022.0,"Nan","Nan","Progrès Niederkorn"]
df.loc[23] = ["Serghei Pașcenco",38,"Moldova","GK","Nan","Nan",33.0,50000,"Nan","Nan","Nan","Nan","Nan"]
df.loc[24] = ["Stefanos Evangelou",23,"Greece","DF","Nan","Nan",41.0,300000,"Nan","Nan","Nan","Nan","Nan"]
df.loc[25] = ["Gustavo Dulanto",26,"Peru","DF","Nan","Nan",55.0,1200000,"Nan",2023.0,"Nan","Nan","Nan"]
df.loc[26] = ["Bruno",27,"Brasil","MF","Nan","Nan",77.0,600000,"Nan",2022.0,"Nan","Nan","Nan"]
df.loc[27] = ["Maxim Cojocaru",23,"Moldova","MF","Nan","Nan",98.0,150000,"Nan","Nan","Nan","Nan","Nan"]
df.loc[28] = ["Momo Yansané",24,"Guinea","FW","Nan","Nan",99.0,1000000,"Nan",2024.0,"Nan","Nan","Nan"]


Tiraspol = df
Tiraspol

,short_name,age,nationality,player_positions,overall,potential,club_jersey_number,value_eur,wage_eur,club_contract_valid_until,international_reputation,release_clause_eur,club_loaned_from
0,Dumitru Celeadnic,29,Moldova,GK,Nan,Nan,1.0,225000,Nan,Nan,Nan,Nan,Nan
1,Danilo Arboleda,26,Colombia,DF,Nan,Nan,2.0,1200000,Nan,Nan,Nan,Nan,Nan
2,Charles Petro,20,Malawi,DF,Nan,Nan,3.0,400000,Nan,2022.0,Nan,Nan,Nan
3,Stjepan Radeljić,24,Bosnia and Herzegovina,DF,Nan,Nan,6.0,350000,Nan,2021.0,Nan,Nan,NK Osijek
4,Basit Khalid,25,Ghana,FW,Nan,Nan,7.0,700000,Nan,2024.0,Nan,Nan,Nan
5,Alexandr Belousov,23,Moldova,DF,Nan,Nan,8.0,300000,Nan,Nan,Nan,Nan,Dinamo-Auto Tiraspol
6,Adama Traoré,26,Mali,FW,Nan,Nan,9.0,2500000,Nan,2022.0,Nan,Nan,FC Metz
7,Frank Castañeda,27,Colombia,FW,Nan,Nan,10.0,1200000,Nan,2021.0,Nan,Nan,Senica
8,Lovro Bizjak,27,Slovenia,FW,Nan,Nan,11.0,400000,Nan,2022.0,Nan,Nan,Nan
9,Abdoul Moumouni,19,Niger,MF,Nan,Nan,12.0,150000,Nan,2024.0,Nan,Nan,Nan
10,Fernando Costanza,22,Brasil,DF,Nan,Nan,13.0,800000,Nan,Nan,Nan,Nan,LOSC Lille
11,Cristiano,28,Brasil,DF,Nan,Nan,15.0,2000000,Nan,2022.0,Nan,Nan,Nan
12,Keston Julien,22,Trinidad and Tobago,DF,Nan,Nan,16.0,450000,Nan,2023.0,Nan,Nan,Nan
13,Jasur Yakhshiboev,24,Uzbekistan,FW,Nan,Nan,17.0,700000,Nan,2022.0,Nan,Nan,Legia Warsaw
14,Moussa Kyabou,23,Mali,MF,Nan,Nan,18.0,350000,Nan,2021.0,Nan,Nan,USC Kita
15,Serafim Cojocari,20,Moldavia,MF,Nan,Nan,19.0,100000,Nan,Nan,Nan,Nan,Nan
16,Boban Nikolov,27,Macedonia,MF,Nan,Nan,20.0,800000,Nan,2022.0,Nan,Nan,Nan
17,Edmund Addo,21,Ghana,MF,Nan,Nan,21.0,Nan,1100000,Nan,2024.0,Nan,Nan
18,Dimitrios Kolovos,28,Greece,MF,Nan,Nan,22.0,1000000,Nan,2022.0,Nan,Nan,Nan
19,Nadrey Dago,24,Ivory Coast,FW,Nan,Nan,23.0,300000,Nan,2023.0,Nan,Nan,NK Dugopolje
20,Dušan Marković,23,Serbia,GK,Nan,Nan,26.0,250000,Nan,Nan,Nan,Nan,Nan
21,Giorgos Athanasiadis,28,Greece,GK,Nan,Nan,30.0,1500000,Nan,2022.0,Nan,Nan,AEK Athens
22,Sébastien Thill,27,Luxembourg,MF,Nan,Nan,31.0,1000000,Nan,2022.0,Nan,Nan,Progrès Niederkorn
23,Serghei Pașcenco,38,Moldova,GK,Nan,Nan,33.0,50000,Nan,Nan,Nan,Nan,Nan
24,Stefanos Evangelou,23,Greece,DF,Nan,Nan,41.0,300000,Nan,Nan,Nan,Nan,Nan
25,Gustavo Dulanto,26,Peru,DF,Nan,Nan,55.0,1200000,Nan,2023.0,Nan,Nan,Nan
26,Bruno,27,Brasil,MF,Nan,Nan,77.0,600000,Nan,2022.0,Nan,Nan,Nan
27,Maxim Cojocaru,23,Moldova,MF,Nan,Nan,98.0,150000,Nan,Nan,Nan,Nan,Nan
28,Momo Yansané,24,Guinea,FW,Nan,Nan,99.0,1000000,Nan,2024.0,Nan,Nan,Nan